language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t omarnava/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true omarnava/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react-2"
  env: "DockerReact2-env"
  bucket_name: "elasticbeanstalk-us-east-1-756514216748"
  bucket_path: "docker-react-2"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
